### ISSUE TITLE
ModuleNotFoundError: No module named 'youtube_transcript_api'

### ISSUE THREAD

**Issue by JaimeMetri** [somanyadav/Youtube-Summariser#3]
Traceback:
File "C:\Users\usr\AppData\Local\Programs\Python\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "C:\Users\usr\Downloads\Youtube-Summariser-main\Youtube-Summariser-main\app.py", line 17, in <module>
    from youtube_transcript_api import YouTubeTranscriptApi

**Comment by somanyadav** [comment]
Will try to fix that tomorrow..

**Comment by somanyadav** [comment]
### Issue Resolved: Running `app.py` with Python 3.8.6

#### System Requirements:
- **Python Version**: 3.8.6

#### Steps to Run `app.py`:
1. **Navigate to the Project Folder**: 
   Ensure you are in the directory where the `app.py` file is located.

2. **Create a Virtual Environment**:
   ```bash
   python -m venv venv
   ```

3. **Activate the Virtual Environment**:
   - For macOS:
     ```bash
     source venv/bin/activate
     ```
   - For Windows:
     ```cmd
     .\venv\Scripts\activate
     ```

4. **Install Required Packages**:
   ```bash
   pip install -r requirements.txt
   ```

5. **Ensure Streamlit is Up-to-Date**:
   ```bash
   pip install streamlit>=1.8.1
   ```

6. **Run the Application**:
   ```bash
   streamlit run app.py
   ```

I was able to successfully run `app.py` in my environment.

**Comment by somanyadav** [comment]
Seems you are using python 3.11
